import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import WhatsappButton from "@/utils/WhatsappButton";
import { CartProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BULLMAN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <WhatsappButton />
          <Navbar />
          <div className="flex min-h-screen flex-col font-mada mt-[140px]">
            {children}
          </div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
